services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: front-desk
    volumes:
      - ./.postgres-data:/var/lib/postgresql
    ports:
      - "5442:5432"
  typesense:
    image: typesense/typesense:29.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./.typesense-data:/data
    command: "--data-dir /data --api-key=typesense-api-key --enable-cors"
